# Generated by Django 4.2.5 on 2023-10-15 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('segment', models.CharField(choices=[('s4', '4 chỗ'), ('s7', '7 chỗ'), ('s16', '16 chỗ'), ('s19', '19 chỗ'), ('s24', '24 chỗ'), ('s35', '35 chỗ')], default=('s4', '4 chỗ'), max_length=100)),
                ('rental', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('describe', models.CharField(max_length=400)),
                ('area', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
